version: 2
updates:
  - package-ecosystem: maven
    directory: '/'
    schedule:
      interval: daily
    # see https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#open-pull-requests-limit
    # open-pull-requests-limit: 10
    versioning-strategy: increase
