= How to release `mvnd`

* Run the https://raw.githubusercontent.com/apache/maven-mvnd/master/build/release-build.sh[release script] which will update the versions, the changelog, the native binaries and will tag the new git commit. This new tag will trigger the https://raw.githubusercontent.com/apache/maven-mvnd/master/.github/workflows/release.yaml[release workflow] on this newly created tag.
[source,shell]
----
./build/release-build.sh <released-version> <next-SNAPSHOT>
----

* While the `darwin-aarch64` is not supported by github, you need to perform a clean build on the tagged branch on a Apple M1 computer and upload the two binary distributions as additional assets to the draft release that has been generated at github.

* Once the workflow completes, run the https://raw.githubusercontent.com/apache/maven-mvnd/master/build/release-candidate.sh[release-candidate script] which will download the built assemblies, compute the checksums and signatures, commit them to the https://dist.apache.org/repos/dist/dev/maven/mvnd/[dev distribution repository]
https://github.com/apache/maven-mvnd/releases[releases] and also upload them as assets to the staging area for the github draft release.
[source,shell]
----
./build/release-candidate.sh <released-version>
----
You can now call a vote on the mailto:dev@maven.apache.org[dev mailing list] pointing to that release candidate.

* Once the vote passes, publish the release using the following command:
[source,shell]
----
./build/release-publish.sh <released-version>
----
WARNING: *TODO*: document the publication process (move to the final svn area, homebrew, sdkman, choco updates...)
